logging:
  level:
    root: WARN

server:
  port: 80

spring:
  application:
    name: media
  resources:
    chain:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

security:
  oauth2:
    client:
      clientId: 607598796084150
      clientSecret: e47959d114672114caac070986b09c02
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
